[localhost]
127.0.0.1 ansible_connection=local

[tantor_nodes]
194_machine ansible_host=192.168.3.194 ansible_user=root ansible_password="Admin@123"

[tantor_nodes:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
