ALTER TABLE hosts ADD COLUMN host_number BIGINT GENERATED ALWAYS AS IDENTITY;
ALTER TABLE hosts ADD CONSTRAINT uq_hosts_host_number UNIQUE (host_number);
ALTER TABLE hosts ADD COLUMN agent_name VARCHAR(255);
ALTER TABLE hosts ADD COLUMN agent_path VARCHAR(1024);
ALTER TABLE hosts ADD COLUMN agent_status VARCHAR(50) NOT NULL DEFAULT 'OFFLINE';

