ALTER TABLE artifact ADD COLUMN IF NOT EXISTS full_file_path VARCHAR(2048);
ALTER TABLE artifact ADD COLUMN IF NOT EXISTS action VARCHAR(40) NOT NULL DEFAULT 'UPLOAD';
ALTER TABLE artifact ADD COLUMN IF NOT EXISTS checksum_md5 CHAR(32);
ALTER TABLE artifact ADD COLUMN IF NOT EXISTS created_by VARCHAR(128) NOT NULL DEFAULT 'system';
ALTER TABLE artifact ADD COLUMN IF NOT EXISTS updated_by VARCHAR(128) NOT NULL DEFAULT 'system';
ALTER TABLE artifact ADD COLUMN IF NOT EXISTS verified_checksum BOOLEAN;
